import type { FlightResult } from '@/types/nva'
import type { BookingPassenger, BookingResult } from '@/services/bookings'

interface Props {
  booking: BookingResult
  flight: FlightResult
  passenger: BookingPassenger
  seat_preference: string
  meal_preference: string
  onClose: () => void
}

const SEAT_LABELS: Record<string, string> = {
  window: 'Window', aisle: 'Aisle', no_preference: 'No preference',
}
const MEAL_LABELS: Record<string, string> = {
  standard: 'Standard', vegetarian: 'Vegetarian', halal: 'Halal', kosher: 'Kosher',
}

export default function BookingConfirmation({ booking, flight, passenger, seat_preference, meal_preference, onClose }: Props) {
  function handleDownload() {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Itinerary ${booking.reference}</title>
  <style>
    body { font-family: 'IBM Plex Sans', Arial, sans-serif; max-width: 600px; margin: 40px auto; color: #111; }
    h1 { color: #1E3A5F; font-size: 22px; margin-bottom: 4px; }
    .ref { font-size: 28px; font-weight: 700; color: #1E3A5F; letter-spacing: 0.05em; margin: 16px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
    th { text-align: left; padding: 8px 12px; background: #f1f5f9; color: #475569; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
    td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
    .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
    @media print { button { display: none; } }
  </style>
</head>
<body>
  <h1>✈ navanVoyageAI — Booking Itinerary</h1>
  <div class="ref">${booking.reference}</div>
  <table>
    <tr><th>Field</th><th>Detail</th></tr>
    <tr><td>Status</td><td>✓ Confirmed</td></tr>
    <tr><td>Flight</td><td>${flight.flight_number} — ${flight.carrier}</td></tr>
    <tr><td>Route</td><td>${flight.origin} → ${flight.destination}</td></tr>
    <tr><td>Date</td><td>${flight.depart_date}</td></tr>
    <tr><td>Cabin</td><td>${flight.cabin_class}</td></tr>
    <tr><td>Passenger</td><td>${passenger.first_name} ${passenger.last_name}</td></tr>
    <tr><td>Passport</td><td>${passenger.passport_number}</td></tr>
    <tr><td>Email</td><td>${passenger.email}</td></tr>
    <tr><td>Seat</td><td>${SEAT_LABELS[seat_preference] ?? seat_preference}</td></tr>
    <tr><td>Meal</td><td>${MEAL_LABELS[meal_preference] ?? meal_preference}</td></tr>
    <tr><td>Total</td><td>$${flight.price_usd.toLocaleString('en-US', { minimumFractionDigits: 2 })} USD</td></tr>
    <tr><td>Booked</td><td>${new Date(booking.created_at).toLocaleString()}</td></tr>
  </table>
  <p class="footer">Generated by navanVoyageAI Corporate Travel Platform. Keep this document for your records.</p>
</body>
</html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `itinerary-${booking.reference}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 20, padding: '8px 0' }}>
      {/* Success badge */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
        <div style={{
          width: 56, height: 56, borderRadius: '50%',
          background: '#D1FAE5', display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 28,
        }}>✓</div>
        <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: '#065F46' }}>Booking Confirmed</h2>
      </div>

      {/* Reference */}
      <div style={{ textAlign: 'center' }}>
        <p style={{ margin: '0 0 4px', fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Reference
        </p>
        <p style={{ margin: 0, fontSize: 24, fontWeight: 700, color: 'var(--navy, #1E3A5F)', fontFamily: 'monospace', letterSpacing: '0.06em' }}>
          {booking.reference}
        </p>
      </div>

      {/* Detail rows */}
      <div style={{ width: '100%', border: '1px solid var(--border)', padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {[
          ['Flight', `${flight.flight_number}  ${flight.origin} → ${flight.destination}  ${flight.depart_date}`],
          ['Passenger', `${passenger.first_name} ${passenger.last_name}`],
          ['Seat', `${SEAT_LABELS[seat_preference] ?? seat_preference}  |  ${flight.cabin_class}`],
          ['Meal', MEAL_LABELS[meal_preference] ?? meal_preference],
          ['Total', `$${flight.price_usd.toLocaleString('en-US', { minimumFractionDigits: 2 })} USD`],
        ].map(([k, v]) => (
          <div key={k} style={{ display: 'flex', gap: 12, fontSize: 'var(--text-sm)' }}>
            <span style={{ width: 80, flexShrink: 0, fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', paddingTop: 1 }}>{k}</span>
            <span style={{ color: 'var(--text-primary)' }}>{v}</span>
          </div>
        ))}
      </div>

      {/* Actions */}
      <div style={{ display: 'flex', gap: 10 }}>
        <button onClick={handleDownload} style={btnOutline}>↓ Download Itinerary</button>
        <button onClick={onClose} style={btnPrimary}>Close</button>
      </div>
    </div>
  )
}

const btnPrimary: React.CSSProperties = {
  padding: '8px 22px', fontSize: 'var(--text-sm)', fontWeight: 700,
  background: 'var(--brand)', color: '#fff', border: 'none', cursor: 'pointer',
}
const btnOutline: React.CSSProperties = {
  padding: '8px 18px', fontSize: 'var(--text-sm)', fontWeight: 600,
  background: 'transparent', color: 'var(--brand)',
  border: '1px solid var(--brand)', cursor: 'pointer',
}
