FROM node:20-alpine AS build

WORKDIR /app
COPY frontend-angular/package*.json ./
RUN npm install

COPY frontend-angular/ .
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/navanvoyageai-angular/browser /usr/share/nginx/html
COPY infrastructure/nginx/spa.conf /etc/nginx/conf.d/default.conf
