FROM node:20-alpine AS build

WORKDIR /app
COPY frontend-angular/package*.json ./
RUN npm ci

COPY frontend-angular/ .
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/navanvoyageai-angular/browser /usr/share/nginx/html
